language: node_js
sudo: false
node_js:
- '8'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_2cb5fc316fec_key -iv $encrypted_2cb5fc316fec_iv
  -in .travis/.id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name x-cold
- git config --global user.email lxstart@outlook.com
install:
- npm install
script:
- npm run deploy
